---
- name: pull git and launch the app with pm2
  hosts: localhost
  vars_files:
    - vars/secrets/secrets.yml
    - vars/variables.yml

  pre_tasks:
    - name: version of Node and NPM
      shell: "node -v && npm -v"
      register: versioninfo

    - name: version info
      debug:
        msg: "version info {{ versioninfo.stdout_lines }}"
      when: versioninfo is changed

  tasks:
    - name: Automatic deploayment
      block:
        - name: Download the code from git repoo to the Test Directory
          git:
            repo: "https://{{ gittoken }}@10.230.189.31/{{ gituser }}/CI2_Engine.git"
            dest: "{{ testDestDir }}"
            single_branch: yes
            version: devRelease

        - name: Reload
          shell: "pm2 stop {{ destdir }}/{{ ciPm2ConfigFile }}"
          register: pm2StopResult

        - name: Run the test cases
          command: npm test
          args:
            chdir: "{{ testDestDir }}"
          register: testcase

        - debug:
            msg: "Test output: {{ testcase.stdout_lines }}"

        - name: Download the code from git repo
              git:
                repo: "https://{{ gittoken }}@10.230.189.31/{{ gituser }}/CI2_Engine.git"
                dest: "{{ destdir }}"
                single_branch: yes
                version: devRelease
      always: 
        - name: starting handlers
          debug:
            msg: Starting handlers

        - name: Start pm2
          shell: "pm2 start {{ destdir }}/{{ ciPm2ConfigFile }}"
          register: pm2Result

        - name: pm2 Info.
          debug:
            msg: "Pm2 output: {{ pm2Result.stdout_lines }}"
