---
- name: pull git and launch the app with pm2
  hosts: localhost
  vars_files:
    - vars/secrets/secrets.yml
    - vars/variables.yml

  pre_tasks:
    - name: version of Node and NPM
      shell: "node -v && npm -v"
      register: versioninfo

    - name: version info
      debug:
        msg: "version info {{ versioninfo.stdout_lines }}"
      when: versioninfo is changed

    - name: Download the code from git repo
      git:
        repo: "https://{{ gittoken }}@10.230.189.31/{{ gituser }}/CI2_Engine.git"
        dest: "{{ destdir }}"
        single_branch: yes
        version: dev
